name: project-management-checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validate Markdown tables
        uses: markdownlint/markdownlint@v1
      - name: Verify task detail references
        run: |
          python scripts/validate_tasks.py
